export default [
  {
    points: "476",
    name: "Max Verstappen",
    flag: "/assets/netherlands-flag.png",
    racerImg: "/assets/ver.png",
    racerNum: "/assets/ver-num.png",
  },
  {
    points: "286",
    name: "Serigo Perez",
    flag: "/assets/mexico-flag.png",
    racerImg: "/assets/per.png",
    racerNum: "/assets/per-num.png",
  },
  {
    points: "216",
    name: "Lewis Hamilton",
    flag: "/assets/uk-flag.png",
    racerImg: "/assets/ham.png",
    racerNum: "/assets/ham-num.png",
  },
  {
    points: "196",
    name: "Fernando Alonso",
    flag: "/assets/spain-flag.png",
    racerImg: "/assets/alo.png",
    racerNum: "/assets/alo-num.png",
  },
  {
    points: "188",
    name: "Carlos Sainz",
    flag: "/assets/spain-flag.png",
    racerImg: "/assets/sai.png",
    racerNum: "/assets/sai-num.png",
  },
  {
    points: "169",
    name: "Charles Leclerc",
    flag: "/assets/monaco-flag.png",
    racerImg: "/assets/lec.png",
    racerNum: "/assets/lec-num.png",
  },
  {
    points: "165",
    name: "Lando Norris",
    flag: "/assets/uk-flag.png",
    racerImg: "/assets/nor.png",
    racerNum: "/assets/nor-num.png",
  },
  {
    points: "136",
    name: "George Russel",
    flag: "/assets/uk-flag.png",
    racerImg: "/assets/rus.png",
    racerNum: "/assets/rus-num.png",
  },
  {
    points: "96",
    name: "Oscar Piastri",
    flag: "/assets/aus-flag.png",
    racerImg: "/assets/pia.png",
    racerNum: "/assets/pia-num.png",
  },
  {
    points: "87",
    name: "Lance Stroll",
    flag: "/assets/canada-flag.png",
    racerImg: "/assets/str.png",
    racerNum: "/assets/str-num.png",
  },
];
